/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentsystem.view;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import studentsystem.model.CurrentGradePassedTableModel;
import studentsystem.model.CurrentGradeStudentTableModel;
import studentsystem.model.CurrentGradeTableModel;
import studentsystem.model.Grade;
import studentsystem.model.GradeTableModel;
import studentsystem.model.Semester;

/**
 *
 * @author Omar
 */
public class PassedGradeWindow extends javax.swing.JFrame {
    
    public static Semester currentSemester;
    Semester semester = null;
    /**
     * Creates new form AssignGradeWindow
     */
    public PassedGradeWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        CurrentGradePassedTableModel model = new CurrentGradePassedTableModel();
        PassedTable.setModel(model);
        for(int i=1; i<LoginWindow.currentStudent.getSemester().listSize();i++){
            try {
                semester = LoginWindow.listaSemestres.getSemesterAt(i);
            } catch (Exception ex) {
                Logger.getLogger(GradeAdministrationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        semesterCb.addItem(String.valueOf(semester.semesterName));
        }
        userLabel.setText(LoginWindow.currentStudent.getName());
        
        ImageIcon backgroundLogoimg = new ImageIcon(getClass().getResource("../systemimages/logo.png"));
        Icon backgroundLogoicn = new ImageIcon(backgroundLogoimg.getImage().getScaledInstance(LogoImageLbl.getWidth(),
                LogoImageLbl.getHeight(), Image.SCALE_DEFAULT));
        LogoImageLbl.setIcon(backgroundLogoicn);
        ImageIcon backgroundUserimg = new ImageIcon(getClass().getResource("../systemimages/login.jpeg"));
        Icon backgroundUsericn = new ImageIcon(backgroundUserimg.getImage().getScaledInstance(userImageLbl.getWidth(),
                userImageLbl.getHeight(), Image.SCALE_DEFAULT));
        userImageLbl.setIcon(backgroundUsericn);
        this.repaint();
        
        semesterCb.addActionListener((ActionEvent e) -> {
            try {
                currentSemester = getSemester();
                
            } catch (Exception ex) {
                Logger.getLogger(PassedGradeWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
           this.dispose();
           PassedGradeWindow c = new PassedGradeWindow();
           c.setVisible(true);
        });
    }
    
    
    public Semester getSemester() throws Exception{
        return LoginWindow.listaSemestres.getSemesterByName((String)semesterCb.getSelectedItem());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoImageLbl = new javax.swing.JLabel();
        userImageLbl = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        semesterCb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PassedTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogoImageLbl.setBackground(new java.awt.Color(0, 0, 0));
        LogoImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentsystem/systemimages/logo.png"))); // NOI18N

        backButton.setText("Atrás");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        semesterCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel3.setText("Semestre");

        PassedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(PassedTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogoImageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userImageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(semesterCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogoImageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userImageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(semesterCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       this.dispose();
       StudentWindow s = new StudentWindow();
       s.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassedGradeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassedGradeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassedGradeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassedGradeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassedGradeWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoImageLbl;
    private javax.swing.JTable PassedTable;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> semesterCb;
    private javax.swing.JLabel userImageLbl;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
