/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentsystem.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import studentsystem.helper.Report;
import studentsystem.model.Grade;
import studentsystem.model.GradeTableModel;
import studentsystem.model.Professor;
import studentsystem.model.ProfessorTableModel;
import studentsystem.model.Semester;
import studentsystem.model.Student;
import studentsystem.model.StudentTableModel;

/**
 *
 * @author Omar
 */
public class Reports extends javax.swing.JFrame {
    
    Report report = new Report();
    
    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        this.setLocationRelativeTo(null);
        for(int i=0; i<GradeTableModel.gradesList.listSize();i++){
            Grade currentGrade = null;
            try {
                currentGrade = GradeTableModel.gradesList.getGradeAt(i);
            } catch (Exception ex) {
                Logger.getLogger(GradeAdministrationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(currentGrade!=null){
                cbCursoReporte1.addItem(currentGrade.getName());
                cbCursoReporte4.addItem(currentGrade.getName());
            }
            
        }
        for(int i=0; i<StudentTableModel.studentsList.listSize();i++){
            Student currentStudent = null;
            try {
                currentStudent = StudentTableModel.studentsList.getStudentAt(i);
            } catch (Exception ex) {
                Logger.getLogger(GradeAdministrationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(currentStudent!=null){
                cbEstudianteReporte2.addItem(currentStudent.getName());
                cbEstudianteReporte3.addItem(currentStudent.getName());
                cbEstudianteReporte9.addItem(currentStudent.getName());
                cbEstudianteReporte10.addItem(currentStudent.getName());
            }   
        }
        for(int i=0; i<ProfessorTableModel.professorsList.listSize();i++){
            Professor currentProfessor = null;
            try {
                currentProfessor = ProfessorTableModel.professorsList.getProfessorAt(i);
            } catch (Exception ex) {
                Logger.getLogger(GradeAdministrationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(currentProfessor!=null){
                cbCatedraticoReporte8.addItem(currentProfessor.getName());
            }   
        }
        for(int i=0; i<LoginWindow.listaSemestres.listSize();i++){
            Semester currentSemester = null;
            try {
                currentSemester = LoginWindow.listaSemestres.getSemesterAt(i);
            } catch (Exception ex) {
                Logger.getLogger(GradeAdministrationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(currentSemester!=null){
                cbSemestreReporte2.addItem(currentSemester.getSemesterName());
                cbSemestreReporte4.addItem(currentSemester.getSemesterName());
                cbSemestreReporte5.addItem(currentSemester.getSemesterName());
                cbSemestreReporte7.addItem(currentSemester.getSemesterName());
                cbSemestreReporte9.addItem(currentSemester.getSemesterName());
            }   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbCursoReporte1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbEstudianteReporte2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbSemestreReporte2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbEstudianteReporte3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbCursoReporte4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbSemestreReporte4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbSemestreReporte5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbSemestreReporte7 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbCatedraticoReporte8 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbEstudianteReporte9 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbSemestreReporte9 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbEstudianteReporte10 = new javax.swing.JComboBox<>();
        generateReport10 = new javax.swing.JButton();
        generateReport9 = new javax.swing.JButton();
        generateReport8 = new javax.swing.JButton();
        generateReport7 = new javax.swing.JButton();
        generateReport6 = new javax.swing.JButton();
        generateReport5 = new javax.swing.JButton();
        generateReport4 = new javax.swing.JButton();
        generateReport3 = new javax.swing.JButton();
        generateReport2 = new javax.swing.JButton();
        generateReport1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Listado de alumnos por curso:");

        cbCursoReporte1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel2.setText("Listado de cursos de estudiante");

        cbEstudianteReporte2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel3.setText("En el semestre");

        cbSemestreReporte2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel4.setText("Listado de cursos aprobados del estudiante");

        cbEstudianteReporte3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel5.setText("Top 3 mejores estudiantes del curso");

        cbCursoReporte4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel6.setText("En el semestre");

        cbSemestreReporte4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel7.setText("Listado de todos los cursos del semestre");

        cbSemestreReporte5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel8.setText("Top de los 5 cursos con más estudiantes");

        jLabel9.setText("Cantidad de alumnos asignados en el semestre");

        cbSemestreReporte7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel10.setText("Cursos que imparte el catedratico");

        cbCatedraticoReporte8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel11.setText("Promedio del estudiante");

        cbEstudianteReporte9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel12.setText("En el semestre");

        cbSemestreReporte9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel13.setText("Promedio general del estudiante");

        cbEstudianteReporte10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        generateReport10.setText("Generar");
        generateReport10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport10ActionPerformed(evt);
            }
        });

        generateReport9.setText("Generar");
        generateReport9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport9ActionPerformed(evt);
            }
        });

        generateReport8.setText("Generar");
        generateReport8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport8ActionPerformed(evt);
            }
        });

        generateReport7.setText("Generar");
        generateReport7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport7ActionPerformed(evt);
            }
        });

        generateReport6.setText("Generar");
        generateReport6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport6ActionPerformed(evt);
            }
        });

        generateReport5.setText("Generar");
        generateReport5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport5ActionPerformed(evt);
            }
        });

        generateReport4.setText("Generar");
        generateReport4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport4ActionPerformed(evt);
            }
        });

        generateReport3.setText("Generar");
        generateReport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport3ActionPerformed(evt);
            }
        });

        generateReport2.setText("Generar");
        generateReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport2ActionPerformed(evt);
            }
        });

        generateReport1.setText("Generar");
        generateReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport1ActionPerformed(evt);
            }
        });

        backBtn.setText("Atrás");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbEstudianteReporte10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSemestreReporte5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCursoReporte4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbCursoReporte1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbEstudianteReporte2, 0, 97, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(13, 13, 13)
                                .addComponent(cbEstudianteReporte3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSemestreReporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSemestreReporte4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCatedraticoReporte8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(cbSemestreReporte7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbEstudianteReporte9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbSemestreReporte9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(generateReport10, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addComponent(generateReport9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReport8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReport7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReport6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReport5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReport4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReport3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReport2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReport1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCursoReporte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbEstudianteReporte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbSemestreReporte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbEstudianteReporte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbCursoReporte4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbSemestreReporte4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbSemestreReporte5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(generateReport6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbSemestreReporte7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbCatedraticoReporte8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbEstudianteReporte9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbSemestreReporte9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbEstudianteReporte10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport10))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport1ActionPerformed
        try {
            report.report1(getGrade(idGrade(cbCursoReporte1)));
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport1ActionPerformed

    private void generateReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport2ActionPerformed
        try {
            report.report2(getStudent(idStudent(cbEstudianteReporte2)), getSemester(idSemester(cbSemestreReporte2)));
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport2ActionPerformed

    private void generateReport5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport5ActionPerformed
        try {
            report.report5(getSemester(idSemester(cbSemestreReporte5)));
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport5ActionPerformed

    private void generateReport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport3ActionPerformed
        try {
            report.report3(getStudent(idStudent(cbEstudianteReporte3)));
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport3ActionPerformed

    private void generateReport7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport7ActionPerformed
        try {
            report.report7(getSemester(idSemester(cbSemestreReporte7)));
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport7ActionPerformed

    private void generateReport8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport8ActionPerformed
        try {
            report.reporte8(getProfessor(idProfessor(cbCatedraticoReporte8)));
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport8ActionPerformed

    private void generateReport9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport9ActionPerformed
        try {
            report.reporte9(getStudent(idStudent(cbEstudianteReporte9)), getSemester(idSemester(cbSemestreReporte9)));
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport9ActionPerformed

    private void generateReport4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport4ActionPerformed
        try {
            report.report4(getGrade(idGrade(cbCursoReporte4)), getSemester(idSemester(cbSemestreReporte4)));
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport4ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        AdministratorWindow window = new AdministratorWindow();
        window.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void generateReport6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport6ActionPerformed
        try {
            report.report6();
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport6ActionPerformed

    private void generateReport10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport10ActionPerformed
        try {
            report.reporte10(getStudent(idStudent(cbEstudianteReporte10)));
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al generar el reporte", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateReport10ActionPerformed
    
    public Student getStudent(int idRef) throws Exception{
        return StudentTableModel.studentsList.getStudentAt(idRef);
    }
    
    public Professor getProfessor(int idRef) throws Exception{
        return ProfessorTableModel.professorsList.getProfessorAt(idRef);
    }
    
    public Grade getGrade(int idRef) throws Exception{
        return GradeTableModel.gradesList.getGradeAt(idRef);
    }
      
    public Semester getSemester(int idRef) throws Exception{
        return LoginWindow.listaSemestres.getSemesterAt(idRef);
    }
    
    public int idSemester(JComboBox cbCombo){
        Semester currentSemester = LoginWindow.listaSemestres.getSemesterByName(String.valueOf(cbCombo.getSelectedItem()));
        return currentSemester.getIdSemester();
    }
    
    public int idGrade(JComboBox cbCombo){
        if(!cbCombo.getSelectedItem().equals("")){
            Grade currentG = GradeTableModel.gradesList.getGradeByName(String.valueOf(cbCombo.getSelectedItem()));
            return currentG.getIdGrade();
        }else{
            return 0;
        }
    }
    public int idProfessor(JComboBox cbCombo){
        if(!cbCombo.getSelectedItem().equals("")){
            Professor currentS = ProfessorTableModel.professorsList.getProfessorByName(String.valueOf(cbCombo.getSelectedItem()));
            return currentS.getIdProfessor();
        }else{
            return 0;
        }
    }
    
    public int idStudent(JComboBox cbCombo){
        if(!cbCombo.getSelectedItem().equals("")){
            Student currentS = StudentTableModel.studentsList.getStudentByName(String.valueOf(cbCombo.getSelectedItem()));
            return currentS.getIdStudent();
        }else{
            return 0;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> cbCatedraticoReporte8;
    private javax.swing.JComboBox<String> cbCursoReporte1;
    private javax.swing.JComboBox<String> cbCursoReporte4;
    private javax.swing.JComboBox<String> cbEstudianteReporte10;
    private javax.swing.JComboBox<String> cbEstudianteReporte2;
    private javax.swing.JComboBox<String> cbEstudianteReporte3;
    private javax.swing.JComboBox<String> cbEstudianteReporte9;
    private javax.swing.JComboBox<String> cbSemestreReporte2;
    private javax.swing.JComboBox<String> cbSemestreReporte4;
    private javax.swing.JComboBox<String> cbSemestreReporte5;
    private javax.swing.JComboBox<String> cbSemestreReporte7;
    private javax.swing.JComboBox<String> cbSemestreReporte9;
    private javax.swing.JButton generateReport1;
    private javax.swing.JButton generateReport10;
    private javax.swing.JButton generateReport2;
    private javax.swing.JButton generateReport3;
    private javax.swing.JButton generateReport4;
    private javax.swing.JButton generateReport5;
    private javax.swing.JButton generateReport6;
    private javax.swing.JButton generateReport7;
    private javax.swing.JButton generateReport8;
    private javax.swing.JButton generateReport9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
